SemestreWork/SemestreWork/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SemestreWork.Pages
{
    public class AboutModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

SemestreWork/SemestreWork/Pages/Authorization.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SemestreWork.Models;
using SemestreWork.Repository;

namespace SemestreWork.Pages
{
    public class AuthorizationModel : PageModel
    {
        IRegisterRepository _usersRepository;
        public AuthorizationModel(IRegisterRepository usersRepository)
        {
            _usersRepository = usersRepository;
        }
        [BindProperty]
        public bool save { get; set; }
        [BindProperty]
        public List<RegisterModel> usersList { get; set; }
        [BindProperty]
        public RegisterModel Anon { get; set; }

        [BindProperty]
        public RegisterModel AuthUser { get; set; }
        [BindProperty]
        public string Message { get; set; }
        public void OnGet()
        {

        }
        public IActionResult OnPost()
        {
            AuthUser = _usersRepository.GetAuthUser(Anon.Email,Crypto.HashPassword(Anon.Password));
            if (AuthUser is null)
            {
                Message = "Не верные данные!";
                return Page();
            }
            else
            {
                HttpContext.Session.Set<RegisterModel>("AuthUser", AuthUser);
                HttpContext.Session.Set("AuthReady", "true");
                HttpContext.Response.Cookies.Append("Email", AuthUser.Email);
                if (save)
                {
                    Random random = new Random();
                    AuthUser.CookieId = random.Next(1, 10000000).ToString();
                    _usersRepository.EditUserCookie(AuthUser);
                    HttpContext.Response.Cookies.Append("CookieId", AuthUser.CookieId);
                }
               
                return Redirect("/Profile/"+AuthUser.Id.ToString());
            }
                
        }
        public IActionResult OnGetLogOut()
        {
            
            var user = HttpContext.Session.Get<RegisterModel>("AuthUser");
            user.CookieId = null;
            _usersRepository.EditUserCookie(user);
            HttpContext.Response.Cookies.Delete("CookieId");
            HttpContext.Session.Clear();
            HttpContext.Session.Set("AuthReady", "false");
            return RedirectToPage("/Home");
        }
    }
}

SemestreWork/SemestreWork/Pages/Cybersport.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SemestreWork.Models;
using SemestreWork.Repository;

namespace SemestreWork.Pages
{
    public class CybersportModel : PageModel
    {
        ICyberKazanRepository _KazanRepository;
        IClobalCyberRepository _GlobalCyber;
        ITopTeamRepository _TopTeamRepository;
        TopPlayersRepository _TopPlayersRepository;
        public CybersportModel(ICyberKazanRepository Repository,IClobalCyberRepository globalCyber, ITopTeamRepository TopTeam, TopPlayersRepository TopPlayersRepository)
        {
            _KazanRepository = Repository;
            _GlobalCyber = globalCyber;
            _TopTeamRepository = TopTeam;
            _TopPlayersRepository = TopPlayersRepository;
        }
        [BindProperty]
        public TopPlayer Topplayer { get; set; }
        [BindProperty]
        public List<TopPlayer> TopPlayersList{ get; set; }
        [BindProperty]
        public TopTeam Topteam { get; set; }
        [BindProperty]
        public List<TopTeam> TopList { get; set; }
        [BindProperty]
        public KazanCyber CyberKazan { get; set; }
        [BindProperty]
        public List<KazanCyber> CyberList { get; set; }
        [BindProperty]
        public GlobalCyber Global { get; set; }
        [BindProperty]
        public List<GlobalCyber> GlobalList{ get; set; }
        public void OnGet()
        {
            CyberList = _KazanRepository.GetList();
            GlobalList = _GlobalCyber.GetList();
            TopList = _TopTeamRepository.GetList();
            TopPlayersList = _TopPlayersRepository.GetList();
        }
        public IActionResult OnPostTop()
        {

            if (ModelState.IsValid)
            {
                var count = _TopTeamRepository.Add(Topteam);
                if (count > 0)
                {
                    return RedirectToPage("/Cybersport");
                }
            }

            return Page();
        }
        public IActionResult OnPostPlayer()
        {

            if (ModelState.IsValid)
            {
                var count = _TopPlayersRepository.Add(Topplayer);
                if (count > 0)
                {
                    return RedirectToPage("/Cybersport");
                }
            }

            return Page();
        }
        public IActionResult OnPostKazan()
        {

            if (ModelState.IsValid)
            {
                var count = _KazanRepository.Add(CyberKazan);
                if (count > 0)
                {
                    return RedirectToPage("/Cybersport");
                }
            }

            return Page();
        }
        public IActionResult OnPostGlobal()
        {

            if (ModelState.IsValid)
            {
                var count = _GlobalCyber.Add(Global);
                if (count > 0)
                {
                    return RedirectToPage("/Cybersport");
                }
            }

            return Page();
        }
        public IActionResult OnPostDeleteGlobal(int id)
        {
            if (id > 0)
            {
                var count = _GlobalCyber.DeleteCyber(id);
                if (count > 0)
                {
                    return RedirectToPage("/Cybersport");
                }
            }

            return Page();

        }
        public IActionResult OnPostDeletePlayer(int id)
        {
            if (id > 0)
            {
                var count = _TopPlayersRepository.DeleteCyber(id);
                if (count > 0)
                {
                    return RedirectToPage("/Cybersport");
                }
            }

            return Page();

        }
        public IActionResult OnPostDeleteTop(int id)
        {
            if (id > 0)
            {
                var count = _TopTeamRepository.DeleteCyber(id);
                if (count > 0)
                {
                    return RedirectToPage("/Cybersport");
                }
            }

            return Page();

        }
        public IActionResult OnPostDeleteKazan(int id)
        {
            if (id > 0)
            {
                var count = _KazanRepository.DeleteCyber(id);
                if (count > 0)
                {
                    return RedirectToPage("/Cybersport");
                }
            }

            return Page();

        }
    }
}

SemestreWork/SemestreWork/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace SemestreWork.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SemestreWork/SemestreWork/Pages/Heroes.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SemestreWork.Pages
{
    public class HeroesModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

SemestreWork/SemestreWork/Pages/Home.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SemestreWork.Models;
using SemestreWork.Repository;

namespace SemestreWork.Pages
{
    public class HomeModel : PageModel
    {
        INewsRepository _Repository;
        public HomeModel(INewsRepository Repository)
        {
            _Repository = Repository;
        }

        [BindProperty]
        public List<NewsPost> newsList { get; set; }

        [BindProperty]
        public NewsPost news { get; set; }

        public void OnGet()
        {
            newsList = _Repository.GetList();
        }
        public IActionResult OnPost()
        {
            string str = HttpUtility.HtmlEncode(news.Text);
            news.Text = str;

            if (ModelState.IsValid)
            {
                var count = _Repository.Add(news);
                if (count > 0)
                {
                    return RedirectToPage("/Home");
                }
            }

            return Page();
        }

        public IActionResult OnPostDelete(int id)
        {
            if (id > 0)
            {
                var count = _Repository.DeleteNews(id);
                if (count > 0)
                {
                    return RedirectToPage("/Home");
                }
            }

            return Page();

        }
    }
}

SemestreWork/SemestreWork/Pages/Meta.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SemestreWork.Models;
using SemestreWork.Repository;

namespace SemestreWork.Pages
{
    public class MetaModel : PageModel
    {
        IMetaRepository metaRepository;
        public MetaModel(IMetaRepository meta)
        {
            metaRepository = meta;
        }
        [BindProperty]
        public MetaPost metaPost { get; set; }

        public string metaTable { get; set; }
        public void OnGet()
        {
            
            metaPost = metaRepository.GetMeta(1);
            metaPost.Text = HttpUtility.HtmlDecode(metaPost.Text);
            metaTable = HttpUtility.HtmlDecode(DotabuffParser("https://ru.dotabuff.com/heroes/winning"));
        }

        public string DotabuffParser(string url)
        {
            string source;
            try { 
            HttpClient client; 
            client = new HttpClient();
            Random random = new Random();
            client.DefaultRequestHeaders.Add("User-Agent", "C# App");
            HttpResponseMessage responce = client.GetAsync(url).Result; 
            source = responce.Content.ReadAsStringAsync().Result;
            var splitMas = source.Split("article");
            source = splitMas[1] ;
            source = source.Remove(0, 1);
            int len = source.Length;
            source = source.Remove(len-2, 2);
            source = source.Replace("sortable", "iksweb");  
            }
            catch
            {
                source = "Статистика пока не доступна!";
            }
            return HttpUtility.HtmlEncode(source);
        }
        
        public IActionResult OnPost()
        {
            var data = metaPost;
            data.Text = HttpUtility.HtmlEncode(metaPost.Text);
            if (ModelState.IsValid)
            {
                var count = metaRepository.EditMeta(data);
                if (count > 0)
                {
                    return Redirect("/Meta");
                }
            }

            return Page();
        }
    }
}

SemestreWork/SemestreWork/Pages/News.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SemestreWork.Models;
using SemestreWork.Repository;


namespace SemestreWork.Pages
{

    public class NewsModel : PageModel
    {
        INewsRepository _Repository;
        ICommentsRepository _commentsRepository;
        public  IRegisterRepository _registerRepository;
        public NewsModel(INewsRepository Repository,ICommentsRepository commentsRepository,IRegisterRepository registerRepository)
        {
            _Repository = Repository;
            _registerRepository = registerRepository;
            _commentsRepository = commentsRepository;
        }

        [BindProperty]
        public Comments comment { get; set; }

        public List<Comments> postsComments { get; set; }

        [BindProperty]
        public NewsPost news { get; set; }


        public string HTMLtext { get;  set; }

        public int Id { get; set; }

        public void OnGet(int id)
        {
               Id = id;
               news = _Repository.GetNews(id);
               HTMLtext = HttpUtility.HtmlDecode(news.Text);
               news.Text = HTMLtext;
            if (postsComments == null)
            {
                postsComments = new List<Comments>();
            }
            postsComments = _commentsRepository.GetList(-id);
        }
        public IActionResult OnPost()
        {
            var data = news;
            data.Text = HttpUtility.HtmlEncode(news.Text);
            if (ModelState.IsValid)
            {
                var count = _Repository.EditNews(data);
                if (count > 0)
                {
                    return Redirect("/Home");
                }
            }

            return Page();
        }

        public IActionResult OnPostSendComment(int id)
        {
            var a = HttpContext.Session.Get<RegisterModel>("AuthUser");
            comment.CreatorId = a.Id;
            comment.CreatorName = a.Nick;
            comment.PostId = -id;
            if (ModelState.IsValid)
            {
                var count = _commentsRepository.Add(comment);
                if (count > 0)
                {
                    return Redirect("/News/"+id);
                }
            }

            return Redirect("/News/" + id);
        }
        public IActionResult OnPostDeleteComment(int id, int ComId)
        {
            if (ComId > 0)
            {
                var count = _commentsRepository.DeleteComment(ComId);
                if (count > 0)
                {
                    return Redirect("/News/" + id);
                }
            }

            return Redirect("/News/" + id);
        }
        public IActionResult OnPostDelete(int id)
        {
            if (id > 0)
            {
                var count = _Repository.DeleteNews(id);
                if (count > 0)
                {
                    return RedirectToPage("/Home");
                }
            }

            return Page();

        }
    }
}

SemestreWork/SemestreWork/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace SemestreWork.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

SemestreWork/SemestreWork/Pages/Registration.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SemestreWork.Models;
using SemestreWork.Repository;

namespace SemestreWork.Pages
{
    public class RegistrationModel : PageModel
    {
        IRegisterRepository _usersRepository;
        public RegistrationModel(IRegisterRepository usersRepository)
        {
            _usersRepository = usersRepository;
        }
        [BindProperty]
        public List<RegisterModel> usersList { get; set; }

        [BindProperty]
        public RegisterModel user { get; set; }
        
        public IActionResult OnPost()
        {
            user.Role = "Default";
            user.Password = Crypto.HashPassword(user.Password);
            if (ModelState.IsValid)
            {
                var count = _usersRepository.AddUser(user);
                if (count > 0)
                {
                    return RedirectToPage("/About");
                }
            }
            return Page();

        }
    }
}

SemestreWork/SemestreWork/Pages/About.cshtml
@page
@model SemestreWork.Pages.AboutModel
@{
    ViewData["Title"] = "About";
}

<!-- main -->
<main class="main align-self-center">
    <div class="container">
        <div class="row">

            <div class="col-2"></div>

            <div class="col-8">
                <h2 align="middle">О проекте</h2>
                <hr>
                <div class="card">
                    <img src="img/forAboutUs.jpeg" alt="Dota 2" width="100%">
                    <div class="card-body">
                        <h4>Что такое AnyMeta?</h4>
                        <p>
                            AnyMeta - это место, где игроки по Dota 2 получают новости об игре,
                            подробную статистику, делятся своими новостями, профилями,
                            и лучше понимают игру, которую мы все любим.
                        </p>

                        <h4>Разделы</h4>
                        <p>
                            Функционал AnyMeta широк. Информация на сайте часто обновляется,
                            что делает его информативным ресурсом по Dota 2.
                            На сайте имеется несколько разделов, которые созданы
                            для удобства поиска нужной информации.
                        </p>

                        <h4>Мета</h4>
                        <p>
                            Мета в Дота 2 – это определенные действия, которые используются большинством
                            игроков для достижения победы в данный момент времени. Она распространяется
                            как на использование определенных героев, так аи на покупаемые предметы.
                            На нашем сайте можно изучить последние мета-отчёты.
                        </p>

                        <h4>Герои</h4>
                        <p>
                            Раздел "Герои" включает в себя список из 10 героев и информацию о них.
                            Также можно изучить история персонажа и проникнуться его лором.
                        </p>

                        <h4>Киберспорт</h4>
                        <p>
                            В этом разделе пользователь может получить актуальные сведения
                            о текущем профессиональном сезоне в г. Казань, киберспортивных командах и их игроках
                            и о послених матчах на про сцене.
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-2"></div>

        </div>
    </div>
</main>

SemestreWork/SemestreWork/Pages/News.cshtml
@page "{id:int}"
@model SemestreWork.Pages.NewsModel
@{
    ViewData["Title"] = "Newss";
}

<!-- main -->
<main class="main align-self-center">
    <div class="container">
        <div class="row">
            <div class="col-2"></div>

            <div class="col-8">
                <div align="right">
                    <h2 align="middle">@Model.news.Name</h2>
                    @using SemestreWork.Models;
                    @if (HttpContext.Session.Get<string>("AuthReady") == "true")
                    {
                        @if (HttpContext.Session.Get<RegisterModel>("AuthUser").Role.ToString() == "Admin")
                        {
                            <form method="post">
                                <button type="submit" asp-page-handler="Delete" asp-route-id="@Model.news.Id" style=" padding: 0;
        border: none;
        font: inherit;
        color: inherit;
        background-color: transparent;
        color: #C0C0C0;
        font-size: 80%;
">
                                    DeletePost [X]
                                </button>
                            </form>
                        }
                    }
                </div>
                <hr>
                <div class="card">
                    <img src="@Model.news.Picture" alt="Dota 2" width="100%">
                    <div class="card-body">
                        @{
                            var str = @Model.HTMLtext;
                        }
                        @Html.Raw(str)
                    </div>
                </div>

                @if (HttpContext.Session.Get<string>("AuthReady") == "true")
                {
                    @if (HttpContext.Session.Get<RegisterModel>("AuthUser").Role.ToString() == "Admin")
                    {
                        <form method="post">
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="panel">
                                            <div class="panel-body">
                                                <div class="col-md-12" style="margin-top:15px;">
                                                    <input asp-for="news.Id" type="hidden" />
                                                    <label asp-for="news.Name" style="font-weight:bold;"></label>
                                                    <input type='text' class='form-control' asp-for="news.Name" />
                                                    <span class="alert-danger" asp-validation-for="news.Name"></span>
                                                </div>
                                                <div class="col-md-12" style="margin-top:15px;">
                                                    <label asp-for="news.Intro" style="font-weight:bold;"></label>
                                                    <textarea style="width:400px;" type='text' class='form-control' asp-for="news.Intro"></textarea>
                                                    <span class="alert-danger" asp-validation-for="news.Intro"></span>
                                                </div>
                                                <div class="col-md-12" style="margin-top:15px;">
                                                    <label asp-for="news.Text" style="font-weight:bold;"></label>
                                                    <textarea style="width:600px; height:150px;" type='text' class='form-control' asp-for="news.Text"></textarea>
                                                    <span class="alert-danger" asp-validation-for="news.Text"></span>
                                                </div>
                                                <div class="col-md-12" style="margin-top:15px;">
                                                    <label asp-for="news.Picture" style="font-weight:bold;"></label>
                                                    <input type='text' class='form-control' asp-for="news.Picture" />
                                                    <span class="alert-danger" asp-validation-for="news.Picture"></span>
                                                </div>

                                                <div class="text-center col-md-12" style="margin-top:35px;">
                                                    <button class="btn btn-primary btn-sx" type="submit"><i class="glyphicon glyphicon-plus"></i> Edit Post</button>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    }
                } 
                
                @foreach (var listComments in Model.postsComments)
                {

                    @if (HttpContext.Session.Get<string>("AuthReady") == "true")
                    {
                        @if (HttpContext.Session.Get<RegisterModel>("AuthUser").Role == "Admin")
                        {
                            <form method="post">
                                <button type="submit" asp-page-handler="DeleteComment" asp-route-ComId="@listComments.Id" style=" padding: 0;
                                                                                    padding-left:90%;
                                                                                    border: none;
                                                                                    font: inherit;
                                                                                    color: inherit;
                                                                                    background-color: transparent;
                                                                                    color: #C0C0C0;
                                                                                    font-size: 100%;
                                                                                                 ">
                                    [X]
                                </button>
                            </form>
                        }
                    }
                    <div >
                        @{ 
                            var comUser = Model._registerRepository.GetUser(@listComments.CreatorId);
                        }
                        <div class="timeline-header">

                            <a class="nav-link" href="~/Profile/@listComments.CreatorId" style="display: inline-block;">
                                <div class="timeline-header">
                                    <span class="userimage">
                                        @if (@comUser.Image == null)
                                        {
                                            <img src="~/img/noavatar.png" style="display: inline-block;">
                                        }
                                        else
                                        {
                                            <img src="@comUser.Image" style="display: inline-block;">
                                        }
                                    </span>
                                    @listComments.CreatorName
                                </div>
</a>
                        </div>
                        @listComments.Text
                        <hr />
                    </div>

                }
                <div class="timeline-comment-box" style="margin-top: 2rem;">
                    <div class="user">
                        <img src="~/img/noavatar.png" alt="Your avatar" width="5%">
                    </div>
                    <div class="input">
                        <form method="post">
                            <div class="input-group">
                                <input type="text" asp-for="comment.Text" class="form-control rounded-corner" placeholder="Напишите что-нибудь...">
                                <span class="alert-danger" asp-validation-for="comment.Text"></span>
                                <div class="input-group-btn p-l-10">
                                    <button asp-page-handler="SendComment" style="margin-left: 1rem;" class="btn btn-primary f-s-12 rounded-corner" type="submit">
                                        Отправить
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>

            <div class="col-2"></div>
        </div>
    </div>
</main>